-- BASE DE DATOS 
create database BD_TransporteUrbano;

use BD_TransporteUrbano;

--drop database BD_TransporteUrbano;

CREATE TABLE BUSES
( 
	BUS_IdBus            int IDENTITY ( 1,1 ) ,
	BUS_Placa            char(06)  NOT NULL ,
	BUS_Capacidad        int  NOT NULL ,
	BUS_Marca            varchar(30)  NOT NULL ,
	BUS_Modelo           varchar(30)  NOT NULL ,
	COND_IdConductor     int  NOT NULL 
)
go



ALTER TABLE BUSES
	ADD CONSTRAINT XPKBUSES PRIMARY KEY  CLUSTERED (BUS_IdBus ASC)
go



CREATE TABLE CONDUCTORES
( 
	COND_IdConductor     int IDENTITY ( 1,1 ) ,
	COND_DNI             char(08)  NOT NULL ,
	COND_Nombres         varchar(50)  NOT NULL ,
	COND_ApellidoPaterno varchar(30)  NOT NULL ,
	COND_ApellidoMaterno varchar(30)  NOT NULL ,
	COND_Telefono        varchar(11)  NOT NULL ,
	COND_FechaNacConductor datetime  NOT NULL ,
	COND_NumeroLicencia  char(9)  NOT NULL 
)
go



ALTER TABLE CONDUCTORES
	ADD CONSTRAINT XPKCONDUCTORES PRIMARY KEY  CLUSTERED (COND_IdConductor ASC)
go



CREATE TABLE CONTROL
( 
	CONT_IdControl       int IDENTITY ( 1,1 ) ,
	CONTUB_IdControlUbicacion int  NOT NULL ,
	RUT_IdRuta           int  NOT NULL ,
	CONT_TiempoAprox     float  NOT NULL 
)
go



ALTER TABLE CONTROL
	ADD CONSTRAINT XPKCONTROL PRIMARY KEY  CLUSTERED (CONT_IdControl ASC)
go



CREATE TABLE CONTROL_UBICACION
( 
	CONTUB_IdControlUbicacion int IDENTITY ( 1,1 ) ,
	CONTUB_Control       varchar(60)  NOT NULL ,
	CONTUB_Codigo        char(5)  NOT NULL ,
	CONTUB_Dirección     varchar(120)  NOT NULL 
)
go



ALTER TABLE CONTROL_UBICACION
	ADD CONSTRAINT XPKCONTOL_UBICACION PRIMARY KEY  CLUSTERED (CONTUB_IdControlUbicacion ASC)
go



CREATE TABLE CONTROLADOR_PERSONAL
( 
	CONTP_IdControlador  int IDENTITY ( 1,1 ) ,
	CONTP_DNI            char(8)  NOT NULL ,
	CONTP_Nombre         varchar(30)  NOT NULL ,
	CONTP_ApellidoPaterno varchar(20)  NOT NULL ,
	CONTP_ApellidoMaterno varchar(20)  NOT NULL 
)
go



ALTER TABLE CONTROLADOR_PERSONAL
	ADD CONSTRAINT XPKCONTROLADOR PRIMARY KEY  CLUSTERED (CONTP_IdControlador ASC)
go



CREATE TABLE CONTROLADOR_SISTEMA
( 
	CONT_IdControl       int  NOT NULL ,
	CONTP_IdControlador  int  NOT NULL ,
	CONTS_NroControl     int  NOT NULL ,
	CONTS_InicioSesion   datetime  NOT NULL ,
	CONTS_HoraSesion     datetime  NOT NULL 
)
go



ALTER TABLE CONTROLADOR_SISTEMA
	ADD CONSTRAINT XPKCONTROLADOR_SISTEMA PRIMARY KEY  CLUSTERED (CONT_IdControl ASC)
go



CREATE TABLE DETALLE_CONTROL
( 
	DCONT_HoraLlegoControl datetime  NOT NULL ,
	DCONT_Fecha          datetime  NOT NULL ,
	DCONT_MontoPenalizacion money  NOT NULL ,
	CONT_IdControl       int  NOT NULL ,
	BUS_IdBus            int  NOT NULL ,
	HCONT_IdHojaControl  int  NOT NULL 
)
go



ALTER TABLE DETALLE_CONTROL
	ADD CONSTRAINT XPKDETALLE_CONTROL PRIMARY KEY  CLUSTERED (CONT_IdControl ASC,BUS_IdBus ASC,HCONT_IdHojaControl ASC)
go



CREATE TABLE DETALLE_RECORRIDO
( 
	DREC_HoraLlegada     datetime  NOT NULL ,
	BUS_IdBus            int  NOT NULL ,
	HCONT_IdHojaControl  int  NOT NULL ,
	DREC_HoraSalida      datetime  NOT NULL ,
	DREC_MontoPenalizacion money  NOT NULL 
)
go



ALTER TABLE DETALLE_RECORRIDO
	ADD CONSTRAINT XPKBUS_SALIDA PRIMARY KEY  CLUSTERED (BUS_IdBus ASC,HCONT_IdHojaControl ASC)
go



CREATE TABLE HOJA_CONTROL_RECORRIDOS
( 
	HCONT_IdHojaControl  int IDENTITY ( 1,1 ) ,
	HCONT_Codigo         char(8)  NOT NULL ,
	HCONT_Fecha          datetime  NOT NULL ,
	HCONT_TotalPenalizacion money  NOT NULL ,
	PEN_IdPenalizacion   int  NOT NULL ,
	HCONT_NVuelta        int  NOT NULL 
)
go



ALTER TABLE HOJA_CONTROL_RECORRIDOS
	ADD CONSTRAINT XPKHOJA PRIMARY KEY  CLUSTERED (HCONT_IdHojaControl ASC)
go



CREATE TABLE PAGO_CONDUCTOR
( 
	COND_IdConductor     int  NOT NULL ,
	PC_Monto             money  NOT NULL ,
	BUS_IdBus            int  NULL ,
	PC_NVuelta           int IDENTITY ( 1,1 ) ,
	PC_Fecha             char(10)  NOT NULL 
)
go



ALTER TABLE PAGO_CONDUCTOR
	ADD CONSTRAINT XPKPAGO_CONDUCTOR PRIMARY KEY  CLUSTERED (PC_NVuelta ASC,PC_Fecha ASC,COND_IdConductor ASC)
go



CREATE TABLE PAGO_CONTROL
( 
	CONT_IdControl       int  NOT NULL ,
	PC_Monto             money  NOT NULL ,
	BUS_IdBus            int  NOT NULL ,
	PC_NVuelta           int IDENTITY ( 1,1 ) ,
	PC_Fecha             char(10)  NOT NULL 
)
go



ALTER TABLE PAGO_CONTROL
	ADD CONSTRAINT XPKPAGO_CONTROL PRIMARY KEY  CLUSTERED (PC_NVuelta ASC,PC_Fecha ASC,CONT_IdControl ASC)
go



CREATE TABLE PENALIZACIONES
( 
	PEN_IdPenalizacion   int IDENTITY ( 1,1 ) ,
	PEN_MontoMinuto      money  NOT NULL ,
	PEN_FechaRegistro    datetime  NOT NULL 
)
go



ALTER TABLE PENALIZACIONES
	ADD CONSTRAINT XPKPENALIZACIONES PRIMARY KEY  CLUSTERED (PEN_IdPenalizacion ASC)
go



CREATE TABLE RUTA
( 
	RUT_IdRuta           int IDENTITY ( 1,1 ) ,
	RUT_Ruta             char(01)  NOT NULL ,
	RUT_CantidadControles int  NOT NULL 
)
go



ALTER TABLE RUTA
	ADD CONSTRAINT XPKRUTA PRIMARY KEY  CLUSTERED (RUT_IdRuta ASC)
go



CREATE TABLE TARIFA
( 
	TAR_IdTarifa         int IDENTITY ( 1,1 ) ,
	TAR_Descripcion      char(30)  NOT NULL 
)
go



ALTER TABLE TARIFA
	ADD CONSTRAINT XPKTarifa PRIMARY KEY  CLUSTERED (TAR_IdTarifa ASC)
go



CREATE TABLE TARIFA_RUTA
( 
	RUT_IdRuta           int  NOT NULL ,
	TR_Monto             money  NOT NULL ,
	TAR_IdTarifa         int  NOT NULL 
)
go



ALTER TABLE TARIFA_RUTA
	ADD CONSTRAINT XPKTarifa_Ruta PRIMARY KEY  CLUSTERED (RUT_IdRuta ASC,TAR_IdTarifa ASC)
go



CREATE TABLE USUARIO
( 
	USU_Usuario          varchar(30)  NOT NULL ,
	USU_Contraseña       varchar(30)  NOT NULL ,
	USU_Correo           varchar(60)  NOT NULL ,
	USU_NombresUsuario   varchar(50)  NOT NULL ,
	USU_ApellidoPaternoUsuario varchar(30)  NOT NULL ,
	USU_ApellidoMaternoUsuario varchar(30)  NOT NULL ,
	USU_FechaNacUsuario  datetime  NOT NULL ,
	USU_IdUsuario        int IDENTITY ( 1,1 ) ,
	USUR_IdUsuarioRol    int  NOT NULL 
)
go



ALTER TABLE USUARIO
	ADD CONSTRAINT XPKUSUARIO PRIMARY KEY  CLUSTERED (USU_IdUsuario ASC)
go



CREATE TABLE USUARIO_ROL
( 
	USUR_Rol             varchar(20)  NOT NULL ,
	USUR_IdUsuarioRol    int IDENTITY ( 1,1 ) 
)
go



ALTER TABLE USUARIO_ROL
	ADD CONSTRAINT XPKROL_USUARIO PRIMARY KEY  CLUSTERED (USUR_IdUsuarioRol ASC)
go




ALTER TABLE BUSES
	ADD CONSTRAINT R_102 FOREIGN KEY (COND_IdConductor) REFERENCES CONDUCTORES(COND_IdConductor)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE CONTROL
	ADD CONSTRAINT R_90 FOREIGN KEY (CONTUB_IdControlUbicacion) REFERENCES CONTROL_UBICACION(CONTUB_IdControlUbicacion)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE CONTROL
	ADD CONSTRAINT R_91 FOREIGN KEY (RUT_IdRuta) REFERENCES RUTA(RUT_IdRuta)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE CONTROLADOR_SISTEMA
	ADD CONSTRAINT R_153 FOREIGN KEY (CONT_IdControl) REFERENCES CONTROL(CONT_IdControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE CONTROLADOR_SISTEMA
	ADD CONSTRAINT R_154 FOREIGN KEY (CONTP_IdControlador) REFERENCES CONTROLADOR_PERSONAL(CONTP_IdControlador)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DETALLE_CONTROL
	ADD CONSTRAINT R_84 FOREIGN KEY (CONT_IdControl) REFERENCES CONTROL(CONT_IdControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DETALLE_CONTROL
	ADD CONSTRAINT R_141 FOREIGN KEY (BUS_IdBus,HCONT_IdHojaControl) REFERENCES DETALLE_RECORRIDO(BUS_IdBus,HCONT_IdHojaControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DETALLE_RECORRIDO
	ADD CONSTRAINT R_142 FOREIGN KEY (BUS_IdBus) REFERENCES BUSES(BUS_IdBus)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DETALLE_RECORRIDO
	ADD CONSTRAINT R_143 FOREIGN KEY (HCONT_IdHojaControl) REFERENCES HOJA_CONTROL_RECORRIDOS(HCONT_IdHojaControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE HOJA_CONTROL_RECORRIDOS
	ADD CONSTRAINT R_88 FOREIGN KEY (PEN_IdPenalizacion) REFERENCES PENALIZACIONES(PEN_IdPenalizacion)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PAGO_CONDUCTOR
	ADD CONSTRAINT R_146 FOREIGN KEY (COND_IdConductor) REFERENCES CONDUCTORES(COND_IdConductor)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PAGO_CONDUCTOR
	ADD CONSTRAINT R_148 FOREIGN KEY (BUS_IdBus) REFERENCES BUSES(BUS_IdBus)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PAGO_CONTROL
	ADD CONSTRAINT R_147 FOREIGN KEY (CONT_IdControl) REFERENCES CONTROL(CONT_IdControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PAGO_CONTROL
	ADD CONSTRAINT R_149 FOREIGN KEY (BUS_IdBus) REFERENCES BUSES(BUS_IdBus)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE TARIFA_RUTA
	ADD CONSTRAINT R_96 FOREIGN KEY (RUT_IdRuta) REFERENCES RUTA(RUT_IdRuta)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE TARIFA_RUTA
	ADD CONSTRAINT R_99 FOREIGN KEY (TAR_IdTarifa) REFERENCES TARIFA(TAR_IdTarifa)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE USUARIO
	ADD CONSTRAINT R_150 FOREIGN KEY (USUR_IdUsuarioRol) REFERENCES USUARIO_ROL(USUR_IdUsuarioRol)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


