-- BASE DE DATOS 
create database BD_TransporteUrbano;
go
use BD_TransporteUrbano;
go

CREATE TABLE BUSES
( 
	BUS_IdBus            int IDENTITY ( 1,1 ) ,
	BUS_Placa            char(06)  NOT NULL ,
	BUS_Capacidad        int  NOT NULL ,
	BUS_Marca            varchar(30)  NOT NULL ,
	BUS_Modelo           varchar(30)  NOT NULL ,
	COND_IdConductor     int  NOT NULL 
)
go



ALTER TABLE BUSES
	ADD CONSTRAINT XPKBUSES PRIMARY KEY  CLUSTERED (BUS_IdBus ASC)
go



CREATE TABLE BUSES_CONTROL
( 
	BUS_IdBus            int  NOT NULL ,
	HCONT_Codigo         char(15)  NOT NULL ,
	CONT_IdControl       int  NULL 
)
go



ALTER TABLE BUSES_CONTROL
	ADD CONSTRAINT XPKBUSES_CONTROL PRIMARY KEY  CLUSTERED (BUS_IdBus ASC,HCONT_Codigo ASC)
go



CREATE TABLE CONDUCTORES
( 
	COND_IdConductor		int IDENTITY ( 1,1 ) ,
	COND_DNI				char(08)  NOT NULL ,
	COND_Nombres			varchar(50)  NOT NULL ,
	COND_ApellidoPaterno	varchar(30)  NOT NULL ,
	COND_ApellidoMaterno	varchar(30)  NOT NULL ,
	COND_Telefono			varchar(11)  NULL ,
	COND_FechaNacConductor	datetime  NOT NULL ,
	COND_NumeroLicencia		char(9)  NULL 
)
go



ALTER TABLE CONDUCTORES
	ADD CONSTRAINT XPKCONDUCTORES PRIMARY KEY  CLUSTERED (COND_IdConductor ASC)
go



CREATE TABLE CONTROL_T
( 
	CONT_IdControl       int IDENTITY ( 1,1 ) ,
	CONTUB_IdControlUbicacion int  NOT NULL ,
	RUT_IdRuta           int  NOT NULL ,
	CONT_TiempoAprox     float  NOT NULL 
)
go



ALTER TABLE CONTROL_T
	ADD CONSTRAINT XPKCONTROL PRIMARY KEY  CLUSTERED (CONT_IdControl ASC)
go



CREATE TABLE CONTROL_UBICACION
( 
	CONTUB_IdControlUbicacion int IDENTITY ( 1,1 ) ,
	CONTUB_Control       varchar(60)  NOT NULL ,
	CONTUB_Codigo        char(5)  NOT NULL ,
	CONTUB_Direccion     varchar(120)  NOT NULL 
)
go



ALTER TABLE CONTROL_UBICACION
	ADD CONSTRAINT XPKCONTOL_UBICACION PRIMARY KEY  CLUSTERED (CONTUB_IdControlUbicacion ASC)
go



CREATE TABLE CONTROLADOR_PERSONAL
( 
	USU_IdUsuario        int  NOT NULL ,
	CONTP_NroControles         int  NOT NULL 
)
go



ALTER TABLE CONTROLADOR_PERSONAL
	ADD CONSTRAINT XPKCONTROLADOR PRIMARY KEY  CLUSTERED (USU_IdUsuario ASC)
go



CREATE TABLE CONTROLADOR_SISTEMA
( 
	CONT_IdControl       int  NOT NULL ,
	CONTS_Autoincremental int IDENTITY ( 1,1 ) ,
	CONTS_InicioSesion   datetime  NOT NULL ,
	CONTS_FinSesion      datetime  NULL ,
	USU_IdUsuario        int  NULL 
)
go



ALTER TABLE CONTROLADOR_SISTEMA
	ADD CONSTRAINT XPKCONTROLADOR_SISTEMA PRIMARY KEY  CLUSTERED (CONT_IdControl ASC,CONTS_Autoincremental ASC)
go



CREATE TABLE DETALLE_CONTROL
( 
	CONT_IdControl			int  NOT NULL ,
	BUS_IdBus				int  NOT NULL ,
	HCONT_IdHojaControl		int  NOT NULL ,
	DREC_Controles			int  NOT NULL ,
	DCONT_FechaHora			datetime  NOT NULL ,
	DCONT_MontoPenalizacion money  NOT NULL ,
	
)
go

alter table DETALLE_CONTROL
  add DCONT_Diferencia float not null default 0

ALTER TABLE DETALLE_CONTROL
	ADD CONSTRAINT XPKDETALLE_CONTROL PRIMARY KEY  CLUSTERED (CONT_IdControl ASC,BUS_IdBus ASC,HCONT_IdHojaControl ASC,DREC_Controles ASC)
go



CREATE TABLE DETALLE_RECORRIDO
( 
	DREC_HoraLlegada     datetime NULL ,
	BUS_IdBus            int NOT NULL ,
	HCONT_IdHojaControl  int NOT NULL ,
	DREC_HoraSalida      datetime NOT NULL ,
	DREC_MontoPenalizacion money NOT NULL ,
	DREC_Controles       int  NOT NULL 
)
go



ALTER TABLE DETALLE_RECORRIDO
	ADD CONSTRAINT XPKBUS_SALIDA PRIMARY KEY  CLUSTERED (BUS_IdBus ASC,HCONT_IdHojaControl ASC,DREC_Controles ASC)
go



CREATE TABLE HOJA_CONTROL_RECORRIDOS
( 
	HCONT_IdHojaControl  int IDENTITY ( 1,1 ) ,
	HCONT_Codigo         char(15)  NOT NULL ,
	HCONT_Fecha          datetime  NOT NULL ,
	HCONT_TotalPenalizacion money  NOT NULL ,
	PEN_IdPenalizacion   int  NOT NULL ,
	HCONT_NVuelta        int  NOT NULL 
)
go



ALTER TABLE HOJA_CONTROL_RECORRIDOS
	ADD CONSTRAINT XPKHOJA PRIMARY KEY  CLUSTERED (HCONT_IdHojaControl ASC)
go


CREATE TABLE OPERACION
( 
	HCONT_IdHojaControl  int  NOT NULL ,
	OPE_Hora		     datetime  NOT NULL ,
	USU_IdUsuario        int  NULL 
)
go



ALTER TABLE OPERACION
	ADD CONSTRAINT XPKOPERACION PRIMARY KEY  CLUSTERED (HCONT_IdHojaControl ASC)
go



CREATE TABLE PAGO_CONTROL
( 
	BUS_IdBus            int  NOT NULL ,
	COND_IdConductor     int  NOT NULL ,
	HCONT_Codigo         char(15)  NOT NULL ,
	PC_Fecha             datetime  NULL ,
	PC_Monto             money  NULL 
)
go



ALTER TABLE PAGO_CONTROL
	ADD CONSTRAINT XPKPAGO_CONTROL PRIMARY KEY  CLUSTERED (BUS_IdBus ASC,COND_IdConductor ASC,HCONT_Codigo ASC)
go



CREATE TABLE PENALIZACIONES
( 
	PEN_IdPenalizacion   int IDENTITY ( 1,1 ) ,
	PEN_MontoMinuto      money  NOT NULL ,
	PEN_FechaRegistro    datetime  NOT NULL 
)
go



ALTER TABLE PENALIZACIONES
	ADD CONSTRAINT XPKPENALIZACIONES PRIMARY KEY  CLUSTERED (PEN_IdPenalizacion ASC)
go



CREATE TABLE RUTA
( 
	RUT_IdRuta           int IDENTITY ( 1,1 ) ,
	RUT_Ruta             char(01)  NOT NULL 
		check(RUT_Ruta in ('A', 'C'))
		default ('A'),
	RUT_CantidadControles int  NOT NULL 
)
go



ALTER TABLE RUTA
	ADD CONSTRAINT XPKRUTA PRIMARY KEY  CLUSTERED (RUT_IdRuta ASC)
go



CREATE TABLE SECRETARIA
( 
	USU_IdUsuario        int  NOT NULL ,
	SEC_Turno                varchar(15)  NOT NULL 
		check(SEC_Turno in ('Mañana', 'Tarde','Noche'))
		default('Mañana')
)
go



ALTER TABLE SECRETARIA
	ADD CONSTRAINT XPKSECRETARI PRIMARY KEY  CLUSTERED (USU_IdUsuario ASC)
go



CREATE TABLE SOLICITUDES
( 
	SOLI_IdSolicitud     int IDENTITY ( 1,1 ) ,
	USU_IdUsuario        int  NOT NULL ,
	USU_Usuario          varchar(30)  NULL ,
	USU_Contrasena       varchar(30)  NULL ,
	USU_Correo           varchar(60)  NULL ,
	USU_DNI              char(8)  NULL ,
	USU_NombresUsuario   varchar(50)  NULL ,
	USU_ApellidoPaternoUsuario varchar(30)  NULL ,
	USU_ApellidoMaternoUsuario varchar(30)  NULL ,
	USU_FechaNacUsuario  datetime  NULL ,
	SOLI_Estado          varchar(10)  NOT NULL ,
	SOLI_Tipo            varchar(15)  NOT NULL 
)
go



ALTER TABLE SOLICITUDES
	ADD CONSTRAINT XPKAPROBACIONES PRIMARY KEY  CLUSTERED (SOLI_IdSolicitud ASC)
go



CREATE TABLE TARIFA
( 
	TAR_IdTarifa         int IDENTITY ( 1,1 ) ,
	TAR_Descripcion      char(30)  NOT NULL 
)
go



ALTER TABLE TARIFA
	ADD CONSTRAINT XPKTarifa PRIMARY KEY  CLUSTERED (TAR_IdTarifa ASC)
go



CREATE TABLE TARIFA_RUTA
( 
	RUT_IdRuta           int  NOT NULL ,
	TR_Monto             money  NOT NULL ,
	TAR_IdTarifa         int  NOT NULL 
)
go



ALTER TABLE TARIFA_RUTA
	ADD CONSTRAINT XPKTarifa_Ruta PRIMARY KEY  CLUSTERED (RUT_IdRuta ASC,TAR_IdTarifa ASC)
go



CREATE TABLE USUARIO
( 
	USU_Usuario						varchar(30)  NOT NULL ,
	USU_Contrasena					varchar(30)  NOT NULL ,
	USU_Correo						varchar(60)  NOT NULL ,
	USU_DNI							char(08)  NOT NULL,
	USU_NombresUsuario				varchar(50)  NOT NULL ,
	USU_ApellidoPaternoUsuario		varchar(30)  NOT NULL ,
	USU_ApellidoMaternoUsuario		varchar(30)  NOT NULL ,
	USU_FechaNacUsuario				datetime  NOT NULL ,
	USU_IdUsuario					int IDENTITY ( 1,1 )
)
go



ALTER TABLE USUARIO
	ADD CONSTRAINT XPKUSUARIO PRIMARY KEY  CLUSTERED (USU_IdUsuario ASC)
go




ALTER TABLE BUSES
	ADD CONSTRAINT R_102 FOREIGN KEY (COND_IdConductor) REFERENCES CONDUCTORES(COND_IdConductor)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE BUSES_CONTROL
	ADD CONSTRAINT R_155 FOREIGN KEY (BUS_IdBus) REFERENCES BUSES(BUS_IdBus)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE BUSES_CONTROL
	ADD CONSTRAINT R_158 FOREIGN KEY (CONT_IdControl) REFERENCES CONTROL_T(CONT_IdControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE CONTROL_T
	ADD CONSTRAINT R_90 FOREIGN KEY (CONTUB_IdControlUbicacion) REFERENCES CONTROL_UBICACION(CONTUB_IdControlUbicacion)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE CONTROL_T
	ADD CONSTRAINT R_91 FOREIGN KEY (RUT_IdRuta) REFERENCES RUTA(RUT_IdRuta)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE CONTROLADOR_PERSONAL
	ADD  FOREIGN KEY (USU_IdUsuario) REFERENCES USUARIO(USU_IdUsuario)
		ON DELETE CASCADE
		ON UPDATE CASCADE
go




ALTER TABLE CONTROLADOR_SISTEMA
	ADD CONSTRAINT R_154 FOREIGN KEY (USU_IdUsuario) REFERENCES CONTROLADOR_PERSONAL(USU_IdUsuario)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE CONTROLADOR_SISTEMA
	ADD CONSTRAINT R_153 FOREIGN KEY (CONT_IdControl) REFERENCES CONTROL_T(CONT_IdControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DETALLE_CONTROL
	ADD CONSTRAINT R_84 FOREIGN KEY (CONT_IdControl) REFERENCES CONTROL_T(CONT_IdControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DETALLE_CONTROL
	ADD CONSTRAINT R_141 FOREIGN KEY (BUS_IdBus,HCONT_IdHojaControl,DREC_Controles) REFERENCES DETALLE_RECORRIDO(BUS_IdBus,HCONT_IdHojaControl,DREC_Controles)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DETALLE_RECORRIDO
	ADD CONSTRAINT R_142 FOREIGN KEY (BUS_IdBus) REFERENCES BUSES(BUS_IdBus)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE DETALLE_RECORRIDO
	ADD CONSTRAINT R_143 FOREIGN KEY (HCONT_IdHojaControl) REFERENCES HOJA_CONTROL_RECORRIDOS(HCONT_IdHojaControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE HOJA_CONTROL_RECORRIDOS
	ADD CONSTRAINT R_88 FOREIGN KEY (PEN_IdPenalizacion) REFERENCES PENALIZACIONES(PEN_IdPenalizacion)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE OPERACION
	ADD CONSTRAINT R_160 FOREIGN KEY (HCONT_IdHojaControl) REFERENCES HOJA_CONTROL_RECORRIDOS(HCONT_IdHojaControl)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE OPERACION
	ADD CONSTRAINT R_161 FOREIGN KEY (USU_IdUsuario) REFERENCES SECRETARIA(USU_IdUsuario)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PAGO_CONTROL
	ADD CONSTRAINT R_156 FOREIGN KEY (BUS_IdBus,HCONT_Codigo) REFERENCES BUSES_CONTROL(BUS_IdBus,HCONT_Codigo)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE PAGO_CONTROL
	ADD CONSTRAINT R_157 FOREIGN KEY (COND_IdConductor) REFERENCES CONDUCTORES(COND_IdConductor)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE SECRETARIA
	ADD  FOREIGN KEY (USU_IdUsuario) REFERENCES USUARIO(USU_IdUsuario)
		ON DELETE CASCADE
		ON UPDATE CASCADE
go




ALTER TABLE SOLICITUDES
	ADD CONSTRAINT R_169 FOREIGN KEY (USU_IdUsuario) REFERENCES USUARIO(USU_IdUsuario)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE TARIFA_RUTA
	ADD CONSTRAINT R_96 FOREIGN KEY (RUT_IdRuta) REFERENCES RUTA(RUT_IdRuta)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE TARIFA_RUTA
	ADD CONSTRAINT R_99 FOREIGN KEY (TAR_IdTarifa) REFERENCES TARIFA(TAR_IdTarifa)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
